# System of Linear Equations with a Unique Solution, Matrix Inverse and the Determinant

The goal of this homework is to learn how to solve systems of linear equations and to be able to compute the determinant and the inverse of an invertible matrix.

**After this assignment you will be able to:**
- Use `NumPy` package to set up the arrays corresponding to the system of linear equations.
- Evaluate the determinant of a matrix and find the solution of the system with `NumPy` linear algebra package.
- Perform row reduction to bring matrix into row echelon form
- Find the solution for the system of linear equations using row reduced approach.
- Compute the inverse of a matrix with `Numpy` linear algebra package and using row reduction approach.

## 1. Solving System of Linear Equations

### 1.1 Row Reduction approach

Solve the following system of linear equations using the reduction method (as mentioned in the week 2 lab):
$$\begin{cases}
x + 2y - 3z + 4w = 12, \\ 2x + 2y - 2z + 3w = 10, \\ y + z = -1, \\ x - y + z - 2w = -4 \end{cases}\tag{1}$$


In [99]:
import numpy as np

In [100]:
A = np.array([
        [1, 2, -3, 4],
        [2, 2, -2, 3],
        [0, 1, 1, 0],
        [1, -1, 1, -2]
    ], dtype=np.dtype(float))

b = np.array([12, 10, -1, -4], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 1.  2. -3.  4.]
 [ 2.  2. -2.  3.]
 [ 0.  1.  1.  0.]
 [ 1. -1.  1. -2.]]

Array b:
[12. 10. -1. -4.]


In [101]:
#CHECKING THE DIMENSIONS OF A AND b
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (4, 4)
Shape of b: (4,)


In [102]:
#PREPARATION FOR ROW-REDUCTION FORM

In [103]:
#FIRST WE NEED TO CREATE THE AUGMENTED MATRIX
A_system = np.hstack((A, b.reshape((4, 1))))
print(A_system)

[[ 1.  2. -3.  4. 12.]
 [ 2.  2. -2.  3. 10.]
 [ 0.  1.  1.  0. -1.]
 [ 1. -1.  1. -2. -4.]]


In [104]:
#CREATING ELEMENATRY ROW OPERATIONS
#row = scalar * row
def MultiplyRow(M, row, scalar):
    M_new = M.copy()
    M_new[row] = M_new[row] * scalar
    return M_new

In [105]:
# row_num_2 = scalar * row_num_1 + row_num_2,
def AddRows(M, row_num_1, row_num_2, scalar):
    M_new = M.copy()
    M_new[row_num_2] = scalar * M_new[row_num_1] + M_new[row_num_2]
    return M_new

In [106]:
# exchange row_num_1 and row_num_2 of the matrix M
def ExchangeRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [107]:
# ROW- ECHELON FORM

In [108]:
# R2 -> R2 - 2*R1
# R4 -> R4 - R1
A_ref = AddRows(A_system,0,1, -2)
A_ref = AddRows(A_ref,0,3, -1)
print(A_ref)

[[  1.   2.  -3.   4.  12.]
 [  0.  -2.   4.  -5. -14.]
 [  0.   1.   1.   0.  -1.]
 [  0.  -3.   4.  -6. -16.]]


In [109]:
# Swap R2 and R3
A_ref = ExchangeRows(A_ref,1,2)
print(A_ref)

[[  1.   2.  -3.   4.  12.]
 [  0.   1.   1.   0.  -1.]
 [  0.  -2.   4.  -5. -14.]
 [  0.  -3.   4.  -6. -16.]]


In [110]:
# R3 -> R3 + 2*R2
# R4 -> R4 + 3R2
A_ref = AddRows(A_ref,1,2, 2)
A_ref = AddRows(A_ref,1,3, 3)
print(A_ref)

[[  1.   2.  -3.   4.  12.]
 [  0.   1.   1.   0.  -1.]
 [  0.   0.   6.  -5. -16.]
 [  0.   0.   7.  -6. -19.]]


In [111]:
# R4 -> R4 - 7/6*R3
# R4 -> 6 * R4
A_ref = AddRows(A_ref,2,3, -7/6)
A_ref = MultiplyRow(A_ref,3,-6) 
print(A_ref)

[[  1.   2.  -3.   4.  12.]
 [  0.   1.   1.   0.  -1.]
 [  0.   0.   6.  -5. -16.]
 [ -0.  -0.  -0.   1.   2.]]


In [112]:
# from the above row echelon form we can dervive the following results:-
w=2
z= (A_ref[2,4]-A_ref[2,3]*w)/A_ref[2,2]
y = (A_ref[1][4] - A_ref[1][2]*z) / A_ref[1][1] 
x = (A_ref[0][4] - A_ref[0][1]*y - A_ref[0][2]*z - A_ref[0][3]*w) / A_ref[0][0]
print(f"The solution to the system of equations is x={x}, y={y}, z={z}, w={w}")

The solution to the system of equations is x=1.0, y=0.0, z=-1.0, w=2


### 1.2 `Numpy` linear algebra package
Solve the above system of linear equations using the `numpy.linalg` package.

In [113]:
s = np.linalg.solve(A, b)
print(f"Solution: {s}")

Solution: [ 1. -0. -1.  2.]


## 2. Determinant
### 2.1 Compute the determinant of matrix $A$ using the `numpy.linalg` package:

$$ \begin{align}
  \textbf{A}  = \begin{bmatrix}
1 & 0 & -2\\
3 & 1 & -2\\
-5 & -1 & 9
\end{bmatrix}
  \end{align}
  $$

In [114]:
A = np.array([
        [1, 0, -2,],
        [3, 1, -2,],
        [-5, -1, 9,]
    ], dtype=np.dtype(float))

det = np.linalg.det(A)
print(f"Determinant of A: {det}")

Determinant of A: 3.000000000000001


### 2.2 Is the above matrix invertible? Why?

Answer here: Yes,the given matrix A is invertible by alegbra test as the determinant of the matrix in non-zero.

# 3. Matrix Inverse
### 3.1 Compute the inverse of non-singular matrix $B$ using row reduction
$$ \begin{align}
  \textbf{B}  = \begin{bmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{bmatrix}
  \end{align}
  $$

In [115]:
B = np.array([
        [1, 2, 1,],
        [4, 4, 5],
        [6, 7, 7,]
    ], dtype=np.dtype(float))
print(B)

[[1. 2. 1.]
 [4. 4. 5.]
 [6. 7. 7.]]


In [116]:
#First we need to create the augmented matrix B | I where I is the identity matrix using the np.hstack and np.eye functions.
B_system = np.hstack((B, np.eye(3))) 
print(B_system)

[[1. 2. 1. 1. 0. 0.]
 [4. 4. 5. 0. 1. 0.]
 [6. 7. 7. 0. 0. 1.]]


In [117]:
# Now we apply row transformations to convert B to the identity matrix, and the identity matrix will transform into B's inverse.

In [118]:
# R2 -> R2 - 4*R1
# R3 -> R3 - 6*R1
B_ref = AddRows(B_system,0,1, -4)
B_ref = AddRows(B_ref,0,2, -6)
print(B_ref)

[[ 1.  2.  1.  1.  0.  0.]
 [ 0. -4.  1. -4.  1.  0.]
 [ 0. -5.  1. -6.  0.  1.]]


In [119]:
# R2 -> R2/-4
B_ref = MultiplyRow(B_ref,1,-1/4)
print(B_ref)

[[ 1.    2.    1.    1.    0.    0.  ]
 [-0.    1.   -0.25  1.   -0.25 -0.  ]
 [ 0.   -5.    1.   -6.    0.    1.  ]]


In [120]:
# R1 -> R1 - 2*R2
# R3 -> R3 + 5*R2
B_ref = AddRows(B_ref,1,0, -2)
B_ref = AddRows(B_ref,1,2, 5)
print(B_ref)

[[ 1.    0.    1.5  -1.    0.5   0.  ]
 [-0.    1.   -0.25  1.   -0.25 -0.  ]
 [ 0.    0.   -0.25 -1.   -1.25  1.  ]]


In [121]:
# R3 -> R3/-0.25
B_ref = MultiplyRow(B_ref,2,-1/0.25)
print(B_ref)    

[[ 1.    0.    1.5  -1.    0.5   0.  ]
 [-0.    1.   -0.25  1.   -0.25 -0.  ]
 [-0.   -0.    1.    4.    5.   -4.  ]]


In [122]:
# R1 -> R1 - 1.5*R3
# R2 -> R2 + 0.25*R3
B_ref = AddRows(B_ref,2,0, -1.5)
B_ref = AddRows(B_ref,2,1,0.25)
print(B_ref)

[[ 1.  0.  0. -7. -7.  6.]
 [-0.  1.  0.  2.  1. -1.]
 [-0. -0.  1.  4.  5. -4.]]


In [124]:
B_inv = B_ref[-3:, -3: ]

In [125]:
print("B's Inverse is:")
print(B_inv)

B's Inverse is:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


### 3.2 Compute the inverse matrix $B$ using the `numpy.linalg` package.

In [123]:
#TODO
print(np.linalg.inv(B))

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
